server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/venue_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root  # 替换为你的MySQL用户名
    password: ASZX3399  # 替换为你的MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true